### ISSUE TITLE
Put figures into repo?

### ISSUE THREAD

**Issue by hammer** [sgkit-dev/sgkit-publication#76]
I'm trying to get an editing workflow going with Overleaf but it doesn't like the missing figures like `figures/data-scaling`. @jeromekelleher is it easy to modify your paper workflow to add these figures to the repo when they stabilize? I don't think it's a big deal if not, I can still read the text, just thought I'd check in case I might be able to clear the errors too!

**Comment by hammer** [comment]
Also their GitHub integration is a little scary it doesn't create a pull request with changes it does a commit and push (cf. https://github.com/overleaf/overleaf/issues/975).

**Comment by jeromekelleher** [comment]
I'll commit the figures in the new year @hammer

I've got a good bit of experience with managing overleaf syncing too, I'll sort it out and send around invites and set out the editing protocols

**Comment by hammer** [comment]
No rush, thanks Jerome!

**Comment by jeromekelleher** [comment]
Closed in #81
